#!/usr/bin/env bash
# Script that displays "To infinity and beyond" forever and is invincible to SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done
